name: Test and create docker image

on:
  pull_request:
  push:
    branches:
      - main
  release:
    types: [created]
  workflow_dispatch:

jobs:
  call-test-workflow:
    if: ${{ (github.ref_name != 'main') }}
    uses: ./.github/workflows/python_test.yaml
