name: Test and create docker image

on:
  pull_request:
  push:
    branches:
      - main
  release:
    types: [created]
  workflow_dispatch:

jobs:
  call-test-workflow:
    if: ${{ (github.ref_name != 'main') }}
    uses: ./.github/workflows/python_test.yaml
  call-semantic-release-workflow:
    if: ${{ (github.ref_name == 'main') && (github.event_name != 'release') && (github.event_name != 'workflow_dispatch') }}
    uses: ./.github/workflows/semantic_release.yaml
